## Pengenalan Array Numpy

In [5]:
import numpy as np

**ndarray** : nama class untuk sebuah array

In [2]:
a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


# properties
* ndarray.ndim: dimensi (rank) dari sebuah numpy array
* ndarray.shape: baris dan kolom dari sebuah numpy array
* ndarray.size: jumlah elemen di dalam numpy array
* ndarray.dtype: tipe data dari elemen yang ada di numpy array
* ndarray.itemsize: ukuran elemen (bytes) yang ada di numpy array
* ndarray.data: buffer untuk menyimpan elemen-elemen di dalam numpy array

In [7]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int32
4


In [8]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int32
4


# membuat numpy arrays

* np.zeros: isinya semua 0
* np.ones: isinya semua 1
* np.arange: bisa berikan scope dan panjang dari step
* np.linspace: berikan scope dan jumlah elemen yang diinginkan
* np.random.random: memberikan angka acak atau random

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(1,4,0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7])

In [12]:
np.linspace(1,4,7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [13]:
np.random.random((3,4))

array([[0.8133129 , 0.28836149, 0.67534771, 0.03188458],
       [0.50935083, 0.78566726, 0.4085139 , 0.32984881],
       [0.45035807, 0.15249118, 0.27631815, 0.41674077]])

# Shape dan Operation

* reshape: mengubah dimensi dari sebuah array
* vstack: stack numpy array secara vertikal
* hstack: stack numpy array secara horizontal
* vsplit
* hsplit

In [5]:
a = np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a = a.reshape(3,-1)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
b = np.array([(7,8),(9,10)])
b 

array([[ 7,  8],
       [ 9, 10]])

In [10]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
c = np.array([(11,12,13),(14,15,16)])
c 

array([[11, 12, 13],
       [14, 15, 16]])

In [14]:
a = np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
d = np.hstack((a,c))
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [17]:
np.vsplit(d,2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [18]:
np.hsplit(d,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [19]:
np.hsplit(d,(1,3)) #split setelah kolum 1 dan kolum 3

[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

# Indexing

In [21]:
data = np.arange(100,200)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [27]:
data2D = data.reshape(10,-1)
data2D

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [26]:
data2D[:,3]

array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [39]:
data2D[1:4,3:5] #baris 123 dan kolom 34

array([[113, 114],
       [123, 124],
       [133, 134]])

# Mathematics array

In [34]:
numbers = np.random.random((5,5))
numbers

array([[0.63941196, 0.88675921, 0.07864792, 0.39802322, 0.66477407],
       [0.44975268, 0.9628914 , 0.39152356, 0.44060035, 0.28633719],
       [0.64036698, 0.4122851 , 0.6314372 , 0.38816541, 0.02637668],
       [0.59723827, 0.91366428, 0.20544589, 0.89707665, 0.73822532],
       [0.03086108, 0.61836578, 0.95162451, 0.39335436, 0.55277622]])

In [36]:
print(np.amin(numbers))
print(np.amax(numbers))
print(np.average(numbers))
print(np.sum(numbers))

0.026376682928146877
0.9628913950634624
0.5278394121230473
13.195985303076183


In [37]:
np.sqrt(numbers)

array([[0.79963239, 0.94167893, 0.28044237, 0.63089081, 0.81533679],
       [0.67063603, 0.9812703 , 0.62571843, 0.66377733, 0.53510484],
       [0.80022933, 0.64209431, 0.79463023, 0.62302922, 0.162409  ],
       [0.77281193, 0.95585788, 0.45326139, 0.94714131, 0.8592004 ],
       [0.17567323, 0.78636237, 0.97551244, 0.62717969, 0.74348922]])

In [46]:
np.cos(numbers) #bisa cari eksponen juga dan lain2

array([[0.80244679, 0.63192704, 0.99690885, 0.92182899, 0.78705618],
       [0.90055465, 0.57114899, 0.92432875, 0.90449579, 0.95928483],
       [0.80187655, 0.91620757, 0.80717996, 0.92560499, 0.99965216],
       [0.82689185, 0.61084867, 0.97897012, 0.62389725, 0.73966404],
       [0.99952383, 0.81482691, 0.58036092, 0.92362857, 0.85107014]])

In [41]:
sample = np.arange(1,21)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
sample2 = np.arange(51,71)
sample2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [45]:
sample + sample2

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90])

# Matrix

In [50]:
matrix = np.random.randint(1,50,20)
matrix = matrix.reshape(4,-1)
matrix

array([[25, 27, 36, 28, 27],
       [22, 22, 26, 14, 29],
       [14, 34,  1, 19, 33],
       [42, 44, 44, 38, 11]])

In [51]:
matrix.transpose()

array([[25, 22, 14, 42],
       [27, 22, 34, 44],
       [36, 26,  1, 44],
       [28, 14, 19, 38],
       [27, 29, 33, 11]])

In [53]:
np.dot(matrix,-1)

array([[-25, -27, -36, -28, -27],
       [-22, -22, -26, -14, -29],
       [-14, -34,  -1, -19, -33],
       [-42, -44, -44, -38, -11]])